### ISSUE TITLE
Have any docs or a simple example of a 2D game?

### ISSUE THREAD

**Issue by JohnAD** [dom96/gamelight#1]
I'd be interested in trying this library out. Have you, by chance, written any small examples or have any docs?

I see that you have a Snake game repo that uses gamelight, but a quick read shows some kind of client/server apects to it. I suspect it was not written to be an exploratory example. :)

Thanks for any help you can provide!

(And thanks for the video feedback the other day.)

**Comment by dom96** [comment]
Sadly no. Snake is all there is I'm afraid. You should still be able to follow its code though :)

**Comment by JohnAD** [comment]
No problem. AFAIK, this is the only game library for Javascript (with Nim).

I'm just experimentally playing with things right now. If I find anything to add, I'll send a PR.
